# This network policy file allows ingress to pods with app=backend in development namespace 
# only from pods with app=frontend in development namespace. Any other ingress connection to 
# pods with app=backend should be blocked
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: limit-ingress-using-podselector
  namespace: development
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      app: backend
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: frontend
